### ISSUE TITLE
RangeError: Maximum call stack size exceeded select2

### ISSUE THREAD

**Issue by ericmaicon** [kartik-v/yii2-widget-select2#107] opened 2015-12-28 16:59 UTC
Hello @kartik-v ,

I am using this widget in a project, and it is awesome, thank you.

After version 2.0.3, it started to give me an error (I didn't change my code, just changed from 2.0.3 to 2.0.4):

my widget:

```php
<?= $form->field($model, 'client_settings_id')->widget(Select2::classname(), [
                'initValueText' => $model->selectedClientName,
                'data' => ArrayHelper::map($clientList, 'id', 'name'),
                'options' => ['placeholder' => 'Select client ...'],
                'pluginOptions' => [
                    'allowClear' => true
                ],
]); ?>
```

my composer:
```
"kartik-v/yii2-widget-select2": "2.0.4",
```

the error:
![captura de tela 2015-12-28 as 14 57 44](https://cloud.githubusercontent.com/assets/1010637/12022053/68aab43a-ad73-11e5-895e-7fb06c1b49a1.png)

I am not sure if the error is with your widget, but since the change of version fixed it, I opened the issue.

The version 2.0.3 works like a charm.

**Comment by kartik-v** [comment] 2015-12-28 18:08
Cannot reproduce your use case.

You may need to check if you have caching issues that is still running old assets - typically clear your web runtime assets directory and browser cache and restart browsers before testing.

**Comment by kartik-v** [comment] 2015-12-29 14:10
BTW the latest stable release is v2.0.6. You may wish to upgrade to that and confirm. Am closing this and if you find something reproducible update in this issue for opening again.

**Closed by kartik-v** 2015-12-29 14:10 UTC

**Comment by ericmaicon** [comment] 2015-12-29 17:20
Hey @kartik-v , I have tested the version 2.0.6 before as well and it didn't work.

Now, I did what you said, I have removed the assets folder and it worked!

thank you.

**Comment by dersonsena** [comment] 2017-12-20 14:41
@kartik-v I'm with same problem. I removed the assets folder and the problem persists. I'm ussing the 2.0.6 version.

```
Uncaught RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at Function.Sizzle [as find] (jquery.js:869)
    at HTMLSpanElement.handlers (jquery.js:4787)
    at HTMLSpanElement.dispatch (jquery.js:4718)
    at HTMLSpanElement.elemData.handle (jquery.js:4549)
    at Object.trigger (jquery.js:7807)
    at HTMLInputElement.<anonymous> (jquery.js:7875)
    at Function.each (jquery.js:365)
    at jQuery.fn.init.each (jquery.js:137)
    at jQuery.fn.init.trigger (jquery.js:7874)
```

A widget call is the same as @ericmaicon
