### ISSUE TITLE
after close i lost the focus (after upgrade to 2.0.9)

### ISSUE THREAD

**Issue by DaveFerger** [kartik-v/yii2-widget-select2#212] opened 2017-05-04 11:57 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-widget-select2.
- [x] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/select2).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] This is not a source plugin (select2) issue. (Those should be directed to the [plugin issues repo](https://github.com/select2/select2/search?q=&type=Issues)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. upgrade to 2.0.9
2. after close i lost the focus

## Expected behavior and actual behavior

expect when selectOnClose => true and highlight a non-selected option and press TAB
in ver. 2.0.8 works well

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- yii2-widget-select2 version:

## Isolating the problem

- [ ] This bug happens [on the widget demos page](http://demos.krajee.com/widget-details/select2)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-widget-select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment] 2017-05-04 12:12
This seems to be due to an update at the source plugin level and happens for single select. It is reproducible on the [plugin's site](https://select2.github.io/examples.html) and needs to be reported there.

Will figure out later an enhancement if not done within the plugin.

**Comment by kartik-v** [comment] 2017-11-24 18:16
Resolved via [update to release v3.1.1](https://github.com/kartik-v/yii2-widget-select2/commit/033c8199174e06368bac683788b28b6e929246c9).

**Closed by kartik-v** 2017-11-24 18:16 UTC
Labels: enhancement
